ALTER TABLE notifications 
MODIFY notification_type ENUM('BOOKING', 'BOOKING_PAYMENT', 'BOOKING_CANCELLED', 'BOOKING_CONFIRMED', 'PAYMENT_RECEIVED', 'REFUND_INITIATED', 'REFUND_COMPLETED', 'WALLET', 'ADMIN_MESSAGE') DEFAULT 'BOOKING_PAYMENT';
